<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Zend Framework テスト</title>
</head>

<body>
<h2><?= $this->title; ?></h2>
<table>
    <?php foreach ($this->rows as $goods): ?>
        <tr>
            <td><?= $goods['goodsID'] ?></td>
            <td><?= $goods['goodsName'] ?></td>
            <td><?= $goods['price'] ?></td>
            <td><?= $goods['goodsNotes'] ?></td>
        </tr>
    <?php endforeach; ?>
</table>
</body>
</html>